---
title: "sex-trade"
format: html
editor: visual
---

```{r}
colors <- c("No" = "#D4D2D2", "Yes" = "black")
```

#### Suffered traumatic brain injuries

```{r}
df <- data.frame(Policy = c("No", "Yes"),
           Count = c(39, 61))

ggplot(df, aes(x = "", y = Count, fill = Policy)) +
  geom_bar(stat = "identity", width = 1) +
  scale_fill_manual(values = colors) +
  coord_polar(theta = "y") +
  theme_void() +
  theme(
    plot.title = element_blank(),
    legend.title = element_blank(),
    legend.position = "bottom"
  )
```

#### PTSD 

```{r}
df <- data.frame(Policy = c("No", "Yes"),
           Count = c(32, 68))

ggplot(df, aes(x = "", y = Count, fill = Policy)) +
  geom_bar(stat = "identity", width = 1) +
  scale_fill_manual(values = colors) +
  coord_polar(theta = "y") +
  theme_void() +
  theme(
    plot.title = element_blank(),
    legend.title = element_blank(),
    legend.position = "bottom"
  )
```

#### Raped, being shot, strangled, burned, beaten, stabbed, or punched.

```{r}
df <- data.frame(Policy = c("No", "Yes"),
           Count = c(7.8, 92.2))

ggplot(df, aes(x = "", y = Count, fill = Policy)) +
  geom_bar(stat = "identity", width = 1) +
  scale_fill_manual(values = colors) +
  coord_polar(theta = "y") +
  theme_void() +
  theme(
    plot.title = element_blank(),
    legend.title = element_blank(),
    legend.position = "bottom"
  )
```
